export type ThemeId =
  | "modern-minimal"
  | "classic-traditional"
  | "bold-colorful"
  | "elegant"
  | "community-friendly"
  | "dark-premium"
  | "faith-warm"
  | "sports-energy"
  | "civic-trust"
  | "nonprofit-heart";

export interface ThemeDefinition {
  id: ThemeId;
  name: string;
  description: string;
  tags: string[];
  variables: Record<string, string>;
}

export const THEMES: ThemeDefinition[] = [
  {
    id: "modern-minimal",
    name: "Modern Minimal",
    description: "Clean blue-gray palette with crisp white space",
    tags: ["professional", "alumni"],
    variables: {
      "--background": "#ffffff",
      "--foreground": "#111827",
      "--muted": "#f3f4f6",
      "--muted-foreground": "#6b7280",
      "--border": "#e5e7eb",
      "--input": "#e5e7eb",
      "--ring": "#2563eb",
      "--primary": "#2563eb",
      "--primary-foreground": "#ffffff",
      "--secondary": "#f3f4f6",
      "--secondary-foreground": "#1f2937",
      "--accent": "#eff6ff",
      "--accent-foreground": "#1e40af",
      "--destructive": "#dc2626",
      "--destructive-foreground": "#ffffff",
      "--success": "#16a34a",
      "--success-foreground": "#ffffff",
      "--warning": "#d97706",
      "--warning-foreground": "#ffffff",
      "--card": "#ffffff",
      "--card-foreground": "#111827",
      "--radius": "0.5rem",
      "--font-heading": "var(--font-inter), system-ui, -apple-system, sans-serif",
      "--font-body": "var(--font-inter), system-ui, -apple-system, sans-serif",
    },
  },
  {
    id: "classic-traditional",
    name: "Classic Traditional",
    description: "Navy, gold, and cream with serif headings",
    tags: ["civic", "professional"],
    variables: {
      "--background": "#faf8f4",
      "--foreground": "#1a1a2e",
      "--muted": "#f0ebe1",
      "--muted-foreground": "#5c5c6e",
      "--border": "#d6cfc3",
      "--input": "#d6cfc3",
      "--ring": "#1b2a4a",
      "--primary": "#1b2a4a",
      "--primary-foreground": "#faf8f4",
      "--secondary": "#f0ebe1",
      "--secondary-foreground": "#1a1a2e",
      "--accent": "#b8952e",
      "--accent-foreground": "#ffffff",
      "--destructive": "#b91c1c",
      "--destructive-foreground": "#ffffff",
      "--success": "#15803d",
      "--success-foreground": "#ffffff",
      "--warning": "#b45309",
      "--warning-foreground": "#ffffff",
      "--card": "#ffffff",
      "--card-foreground": "#1a1a2e",
      "--radius": "0.375rem",
      "--font-heading": "var(--font-playfair-display), Georgia, 'Times New Roman', serif",
      "--font-body": "var(--font-source-sans-3), system-ui, -apple-system, sans-serif",
    },
  },
  {
    id: "bold-colorful",
    name: "Bold & Colorful",
    description: "Vibrant purple, pink, and orange for energetic orgs",
    tags: ["sports", "other"],
    variables: {
      "--background": "#fefefe",
      "--foreground": "#1e1b2e",
      "--muted": "#f5f0ff",
      "--muted-foreground": "#64608a",
      "--border": "#e0d4f5",
      "--input": "#e0d4f5",
      "--ring": "#7c3aed",
      "--primary": "#7c3aed",
      "--primary-foreground": "#ffffff",
      "--secondary": "#fef3f2",
      "--secondary-foreground": "#9f1239",
      "--accent": "#db2777",
      "--accent-foreground": "#ffffff",
      "--destructive": "#e11d48",
      "--destructive-foreground": "#ffffff",
      "--success": "#059669",
      "--success-foreground": "#ffffff",
      "--warning": "#ea580c",
      "--warning-foreground": "#ffffff",
      "--card": "#ffffff",
      "--card-foreground": "#1e1b2e",
      "--radius": "0.75rem",
      "--font-heading": "var(--font-poppins), system-ui, -apple-system, sans-serif",
      "--font-body": "var(--font-poppins), system-ui, -apple-system, sans-serif",
    },
  },
  {
    id: "elegant",
    name: "Elegant",
    description: "Dark backgrounds with gold accents, premium feel",
    tags: ["alumni", "professional"],
    variables: {
      "--background": "#1a1a28",
      "--foreground": "#ece9e1",
      "--muted": "#282838",
      "--muted-foreground": "#9e9aaa",
      "--border": "#383848",
      "--input": "#383848",
      "--ring": "#c9a84c",
      "--primary": "#c9a84c",
      "--primary-foreground": "#1a1a28",
      "--secondary": "#282838",
      "--secondary-foreground": "#ece9e1",
      "--accent": "#d4af5c",
      "--accent-foreground": "#1a1a28",
      "--destructive": "#f87171",
      "--destructive-foreground": "#1a1a28",
      "--success": "#4ade80",
      "--success-foreground": "#1a1a28",
      "--warning": "#fbbf24",
      "--warning-foreground": "#1a1a28",
      "--card": "#222234",
      "--card-foreground": "#ece9e1",
      "--radius": "0.25rem",
      "--font-heading": "var(--font-cormorant-garamond), Georgia, serif",
      "--font-body": "var(--font-nunito-sans), system-ui, -apple-system, sans-serif",
    },
  },
  {
    id: "community-friendly",
    name: "Community Friendly",
    description: "Warm greens and earth tones with rounded shapes",
    tags: ["hoa", "nonprofit"],
    variables: {
      "--background": "#f8faf8",
      "--foreground": "#1a2e1a",
      "--muted": "#ecf5ec",
      "--muted-foreground": "#5a6e5a",
      "--border": "#c8ddc8",
      "--input": "#c8ddc8",
      "--ring": "#0f766e",
      "--primary": "#0f766e",
      "--primary-foreground": "#ffffff",
      "--secondary": "#ecf5ec",
      "--secondary-foreground": "#0f766e",
      "--accent": "#d97706",
      "--accent-foreground": "#ffffff",
      "--destructive": "#dc2626",
      "--destructive-foreground": "#ffffff",
      "--success": "#15803d",
      "--success-foreground": "#ffffff",
      "--warning": "#ca8a04",
      "--warning-foreground": "#ffffff",
      "--card": "#ffffff",
      "--card-foreground": "#1a2e1a",
      "--radius": "0.75rem",
      "--font-heading": "var(--font-nunito), system-ui, -apple-system, sans-serif",
      "--font-body": "var(--font-nunito), system-ui, -apple-system, sans-serif",
    },
  },
  {
    id: "dark-premium",
    name: "Dark Premium",
    description: "Charcoal and electric blue, modern tech-forward look",
    tags: ["professional", "other"],
    variables: {
      "--background": "#0c0e16",
      "--foreground": "#e2e4ea",
      "--muted": "#1a1d2b",
      "--muted-foreground": "#8b8fa0",
      "--border": "#282c3e",
      "--input": "#282c3e",
      "--ring": "#3b82f6",
      "--primary": "#3b82f6",
      "--primary-foreground": "#ffffff",
      "--secondary": "#1a1d2b",
      "--secondary-foreground": "#e2e4ea",
      "--accent": "#06b6d4",
      "--accent-foreground": "#0c0e16",
      "--destructive": "#f43f5e",
      "--destructive-foreground": "#ffffff",
      "--success": "#22d3ee",
      "--success-foreground": "#0c0e16",
      "--warning": "#facc15",
      "--warning-foreground": "#0c0e16",
      "--card": "#141727",
      "--card-foreground": "#e2e4ea",
      "--radius": "0.5rem",
      "--font-heading": "var(--font-space-grotesk), system-ui, -apple-system, sans-serif",
      "--font-body": "var(--font-dm-sans), system-ui, -apple-system, sans-serif",
    },
  },
  {
    id: "faith-warm",
    name: "Faith & Warmth",
    description: "Warm burgundy and cream with gold touches",
    tags: ["church"],
    variables: {
      "--background": "#fdf8f4",
      "--foreground": "#2d1a1a",
      "--muted": "#f5ebe3",
      "--muted-foreground": "#6e5555",
      "--border": "#e0d0c4",
      "--input": "#e0d0c4",
      "--ring": "#7f1d1d",
      "--primary": "#7f1d1d",
      "--primary-foreground": "#fdf8f4",
      "--secondary": "#f5ebe3",
      "--secondary-foreground": "#7f1d1d",
      "--accent": "#a16207",
      "--accent-foreground": "#ffffff",
      "--destructive": "#b91c1c",
      "--destructive-foreground": "#ffffff",
      "--success": "#166534",
      "--success-foreground": "#ffffff",
      "--warning": "#92400e",
      "--warning-foreground": "#ffffff",
      "--card": "#fffdfb",
      "--card-foreground": "#2d1a1a",
      "--radius": "0.375rem",
      "--font-heading": "var(--font-lora), Georgia, 'Times New Roman', serif",
      "--font-body": "var(--font-open-sans), system-ui, -apple-system, sans-serif",
    },
  },
  {
    id: "sports-energy",
    name: "Sports Energy",
    description: "Bold red and charcoal with strong typography",
    tags: ["sports"],
    variables: {
      "--background": "#fafafa",
      "--foreground": "#171717",
      "--muted": "#f0f0f0",
      "--muted-foreground": "#525252",
      "--border": "#d4d4d4",
      "--input": "#d4d4d4",
      "--ring": "#b91c1c",
      "--primary": "#b91c1c",
      "--primary-foreground": "#ffffff",
      "--secondary": "#262626",
      "--secondary-foreground": "#fafafa",
      "--accent": "#f59e0b",
      "--accent-foreground": "#171717",
      "--destructive": "#dc2626",
      "--destructive-foreground": "#ffffff",
      "--success": "#16a34a",
      "--success-foreground": "#ffffff",
      "--warning": "#d97706",
      "--warning-foreground": "#ffffff",
      "--card": "#ffffff",
      "--card-foreground": "#171717",
      "--radius": "0.25rem",
      "--font-heading": "var(--font-oswald), 'Impact', system-ui, sans-serif",
      "--font-body": "var(--font-roboto), system-ui, -apple-system, sans-serif",
    },
  },
  {
    id: "civic-trust",
    name: "Civic Trust",
    description: "Deep blue and silver, clean and authoritative",
    tags: ["civic", "hoa"],
    variables: {
      "--background": "#f8f9fb",
      "--foreground": "#0f172a",
      "--muted": "#eef1f5",
      "--muted-foreground": "#64748b",
      "--border": "#cbd5e1",
      "--input": "#cbd5e1",
      "--ring": "#1e3a5f",
      "--primary": "#1e3a5f",
      "--primary-foreground": "#ffffff",
      "--secondary": "#eef1f5",
      "--secondary-foreground": "#1e3a5f",
      "--accent": "#475569",
      "--accent-foreground": "#ffffff",
      "--destructive": "#dc2626",
      "--destructive-foreground": "#ffffff",
      "--success": "#15803d",
      "--success-foreground": "#ffffff",
      "--warning": "#b45309",
      "--warning-foreground": "#ffffff",
      "--card": "#ffffff",
      "--card-foreground": "#0f172a",
      "--radius": "0.375rem",
      "--font-heading": "var(--font-plus-jakarta-sans), system-ui, -apple-system, sans-serif",
      "--font-body": "var(--font-plus-jakarta-sans), system-ui, -apple-system, sans-serif",
    },
  },
  {
    id: "nonprofit-heart",
    name: "Nonprofit Heart",
    description: "Warm coral and teal with friendly, rounded shapes",
    tags: ["nonprofit"],
    variables: {
      "--background": "#fefcfa",
      "--foreground": "#1c1917",
      "--muted": "#fdf2ec",
      "--muted-foreground": "#78716c",
      "--border": "#e7d9cf",
      "--input": "#e7d9cf",
      "--ring": "#e05a3a",
      "--primary": "#d14f30",
      "--primary-foreground": "#ffffff",
      "--secondary": "#eef9f7",
      "--secondary-foreground": "#0f766e",
      "--accent": "#0d9488",
      "--accent-foreground": "#ffffff",
      "--destructive": "#dc2626",
      "--destructive-foreground": "#ffffff",
      "--success": "#059669",
      "--success-foreground": "#ffffff",
      "--warning": "#ca8a04",
      "--warning-foreground": "#ffffff",
      "--card": "#ffffff",
      "--card-foreground": "#1c1917",
      "--radius": "1rem",
      "--font-heading": "var(--font-quicksand), system-ui, -apple-system, sans-serif",
      "--font-body": "var(--font-nunito), system-ui, -apple-system, sans-serif",
    },
  },
];

export function getThemeById(id: string): ThemeDefinition {
  return THEMES.find((t) => t.id === id) || THEMES[0];
}

const DARK_THEMES: ThemeId[] = ["elegant", "dark-premium"];

export function isDarkTheme(id: string): boolean {
  return DARK_THEMES.includes(id as ThemeId);
}

const ORG_TYPE_THEME_MAP: Record<string, ThemeId[]> = {
  civic: ["civic-trust", "classic-traditional", "modern-minimal"],
  nonprofit: ["nonprofit-heart", "community-friendly", "bold-colorful"],
  church: ["faith-warm", "classic-traditional", "elegant"],
  sports: ["sports-energy", "bold-colorful", "dark-premium"],
  hoa: ["civic-trust", "community-friendly", "modern-minimal"],
  professional: ["modern-minimal", "dark-premium", "classic-traditional"],
  alumni: ["elegant", "classic-traditional", "modern-minimal"],
  other: ["modern-minimal", "community-friendly", "bold-colorful"],
};

export function getRecommendedThemes(orgType: string): ThemeDefinition[] {
  const ids = ORG_TYPE_THEME_MAP[orgType] || ORG_TYPE_THEME_MAP.other;
  return ids
    .map((id) => THEMES.find((t) => t.id === id))
    .filter((t): t is ThemeDefinition => t !== undefined);
}
